### ISSUE TITLE
Provide standalone js package

### ISSUE THREAD

**Issue by Patricks15** [project-nv/night-vision#100]
### Description

Hello, 
this project looks really amazing to me. I would love to use this.
But I need it as a standalone package for a static html import. Is there a way to provide this js chart library as a standalone package?

Best regards,
Patrick

### Suggested solution

E.g.: provide it as a standalone package by cdn or unpkg.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Thanks man. Yeah, you know what, it actually can be useful. For now you need to run `npm run build-cdn` in the repo. Cdn version will be in `dist/cdn`. To use:

```
let chart = new NightVision.NightVision(...)
```
