### ISSUE TITLE
 intraday intraday chart

### ISSUE THREAD

**Issue by smofor** [project-nv/night-vision#101]
### Description

This is a great stock chart. I want to create an intraday intraday chart, and I need to specify to display 300 K-line charts. Where can I make changes, fix the width, or something like that?
<img width="1035" alt="pingguo" src="https://github.com/project-nv/night-vision/assets/14040089/274c974b-249d-40a7-a6be-6c4791996f97">

### Suggested solution

This is a great stock chart. I want to create an intraday intraday chart, and I need to specify to display 300 K-line charts. Where can I make changes, fix the width, or something like that?
<img width="1035" alt="pingguo" src="https://github.com/project-nv/night-vision/assets/14040089/274c974b-249d-40a7-a6be-6c4791996f97">

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
You can try to use `Splines` overlay. But it will be a mess (300 lines)

**Comment by smofor** [comment]
> You can try to use `Splines` overlay. But it will be a mess (300 lines)
I attempted it, but it affected my real-time data updates. Is there a better way to achieve this?

**Comment by smofor** [comment]
Real-time updating data will recognize the last timestamp in the overlaying layer.

**Comment by C451** [comment]
Splines is the fastest way. Make sure it's set as the main overlay, then push updates as on a regular chart
