### ISSUE TITLE
Gap between candles because of missing weekend data

### ISSUE THREAD

**Issue by Patricks15** [project-nv/night-vision#104]
### Description

Is there a way to close the gaps between candles, if I only have data for 5 days of the week? 
So Saturday and Sunday are missing in my data row. (See the screenshot below). Because of that missing days, there is I gap in the chart, I don't like.

I  also tried to switch between timestamp and index format, but then I lost the nice timeline on the x-axis.

### Suggested solution

Is there already a solution for this problem?
My solution would be related to the x axis format?
Or can I provide a separate time data, than for all overlays?

Thank you for your help and best regards.

### Additional context

<img width="744" alt="image" src="https://github.com/project-nv/night-vision/assets/113530941/6de7a87f-daa6-4bf4-b2fa-51eb8f9c884b">

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Patricks15** [comment]
I added  a codesandbox for reproduction and debugging.
I build night-vision.min.js on my own and added it.

https://codesandbox.io/embed/debug-night-vision-n7rqcx?fontsize=14&hidenavigation=1&theme=dark

**Comment by robinhuse** [comment]
You can pass indexBased: true in your data configuration to close the gaps.
`{
    "indexBased": true,
    "panes": [
        {
            "overlays": [...`

**Comment by Patricks15** [comment]
Perfect, that is working. Thank you
