### ISSUE TITLE
Multiple Main Overlay

### ISSUE THREAD

**Issue by wk1210** [project-nv/night-vision#105]
### Description

I currently have this requirement: I use built-in indicators like MACD in the framework to calculate a numerical MACD, but this numerical value is not OHLCV, but another value calculated. However, the built-in indicators in the framework currently use OHLCV data as the main overlay, and I found through testing that even if I create another pane and pass in the calculated value, I cannot use that value with the built-in indicators. Is there another way to meet this requirement? Looking forward to your reply.

### Suggested solution

I currently don't have any suggestions.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Datasets that were used in TVJS is not tested/implemented yet. But you could make a hack putting your data in the main (hiding it), adding candles as overlay.

**Comment by wk1210** [comment]
> Datasets that were used in TVJS is not tested/implemented yet. But you could make a hack putting your data in the main (hiding it), adding candles as overlay.

Thank you very much, I'll try it.
