### ISSUE TITLE
Cursor behavior on mobile device

### ISSUE THREAD

**Issue by RazvanMudura** [project-nv/night-vision#106]
### Description

I tried creating a moving cursor in Night Vision for when the user enters the application from the phone.
I am aware that Night Vision doesn't still have a mobile support, and this feature is in the roadmap.

When on a mobile device, I attached to the div on which the canvas renders, some functions on touch start, end and move events, and then simulated a trackpad similar to the one on TradingView, but sometimes when a default touch is generated, the night-vision cursor overrides mine and moves in the position of my finger, even tough I don't want this behavior to occur.

I tried disabling it by emitting the event "cursor-locked" with a "true" value as the second parameter but to no avail.
The pointer object in "/core/input/pointer.js" has a method from HammerJS which by default on a tap overrides my cursor.

Is there a way in which I could disable this default behavior of the cursor?

**Here is a demo of the issue:**
![](https://cdn.discordapp.com/attachments/496004508674031640/1172218722165993572/ezgif.com-video-to-gif.gif)

**Here is a oversimplified version of my code:**
```js
  // Function to move the cursor based on the touch input
  const moveCursor = (x, y) => {
      const obj = {
          gridId: 0,
          x,
          y,
          visible: true,
          show: true
      }

      chart.events.emit('cursor-changed', obj)
      chart.events.emit('cursor-locked', true)
      chart.events.emit('scroll-lock', true)
  }
  
  // Function to turn on the cursor
    const activateCursor = (x, y) => {
            const obj = {
                gridId: 0,
                x,
                y,
                visible: true,
                show: true
            }

            chart.events.emit('cursor-changed', obj)
            chart.events.emit('cursor-locked', true)
            chart.events.emit('scroll-lock', true)

            cursorActive = true
        }
    }
```

### Suggested solution

I know that the solution is in the making as seen in the roadmap, but maybe a new path to achieve this behavior.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Not properly ported to mobile yet.
