### ISSUE TITLE
Line tool future line types

### ISSUE THREAD

**Issue by RazvanMudura** [project-nv/night-vision#107]
### Description

Regarding the line tool implemented recently.
Are there going to be more types of lines added in the future to the line tool, not only the segment, for example the horizontal line or trend line?

### Suggested solution

.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Yes, In the future.
