### ISSUE TITLE
The indicator chart is incorrect.

### ISSUE THREAD

**Issue by oxxxxxy** [project-nv/night-vision#116]
### Describe the bug

![image](https://github.com/project-nv/night-vision/assets/99099523/8a2795b9-270e-45f1-ad45-699f7039d1fc)

I expect a MACD chart, but i can't see its chart draw, it has generated title thing only. One value is in its overlay dataset( chart object via console ) only.

Main overlay has klines, they are okay. I didn't forget about this thing `chart.se.uploadAndExec()`, nothing changes. 

Did I misunderstand how the indicator script works or didn't i read docs enough? Should indicator chart be drawn completely by script or should i have to somehow calculate, collect the values and draw it by myself? :sweat_smile: :sweat_smile: :sweat_smile:  For example, make predefined overlay with range and insert into it calculated values.

So... _sir ples du help_ 

```

{
  "panes": [
    {
      "overlays": [
        {
          "name": "dbPairId88",
          "type": "Candles",
          "main": true,
          "data": [
            [1707892200000, 0.08221, 0.08226, 0.08214, 0.0822, 600614],
            ........
            [1707534000000, 0.07945, 0.07979, 0.07941, 0.07953, 3825781]
          ],
          "settings": {},
          "props": {
            "showVolume": false
          }
        }
      ]
    },
    {
      "overlays": [],
      "scripts": [
        {
          "type": "MACD",
          "props": {},
          "settings": {}
        }
      ]
    }
  ]
}
```

### Reproduction

https://codesandbox.io/p/devbox/3yk8x6?migrateFrom=6kfp8c&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt68p5380006206827ojvzxh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt68p53800022068l49wgk86%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt68p538000420681rvg2qjp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt68p53800052068pprwret0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt68p53800022068l49wgk86%2522%253A%257B%2522id%2522%253A%2522clt68p53800022068l49wgk86%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt68p53800052068pprwret0%2522%253A%257B%2522id%2522%253A%2522clt68p53800052068pprwret0%2522%252C%2522activeTabId%2522%253A%2522clt68r12l00ja2068gv70d939%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clt68r12l00ja2068gv70d939%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt68p538000420681rvg2qjp%2522%253A%257B%2522id%2522%253A%2522clt68p538000420681rvg2qjp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt68p53800032068lne53543%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt68omh8000bdcf85ako14bo%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt68p53800032068lne53543%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Just open link)))

### Javascript Framework

no-framework (vanilla-js)

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oxxxxxy** [comment]
ping...

**Comment by oxxxxxy** [comment]
N

**Comment by oxxxxxy** [comment]
I

**Comment by oxxxxxy** [comment]
ce :+1:

**Comment by oxxxxxy** [comment]
hey, you, who looking for answer.

this is it https://github.com/wrule/tulip-wasm-old

if you want to calc all that _shit_ in client.

**Comment by oxxxxxy** [comment]
lan, pohuy... ya uje neskolko raz izmenil, ne fakt chto est dannie dlya otrabotki. krch... tam escho takaya huynya vilezla, chto ne mogu zoomit' blije, tolko dalshe, v chem delo hz. svechi s primera zoomyatsya, a tekuschie svechi net...

ochen' jal', mne proekt za svoyu prostotu och ponravilsya.
It's a pity, I really liked the project for its simplicity.

![image](https://github.com/project-nv/night-vision/assets/99099523/74e2127f-264d-42fd-a661-6898148abc62)

**Comment by oxxxxxy** [comment]
![image](https://github.com/project-nv/night-vision/assets/99099523/f0c585bb-d000-4d3b-86da-dc493b1a5060)
![image](https://github.com/project-nv/night-vision/assets/99099523/0252a302-9e7f-466a-bf63-9a8bcc1fd6f5)

how about that?

**Comment by oxxxxxy** [comment]
![image](https://github.com/project-nv/night-vision/assets/99099523/1a9e968a-868d-44bf-bdd8-0abae5262815)
oh my goooooood
guess what. yes, there is problem with zooming. and this problem is BIG AS F... Finsteraarhorn ( mountain ).

**Comment by oxxxxxy** [comment]
вот что реально круто у либы твоей, так это простота.

**Comment by mrzafod** [comment]
> вот что реально круто у либы твоей, так это простота.

Салам алейкум! 
Я так понял ты уже какое-то время используешь этот пакет. Можешь дать обратку? Стоит ее форкать и ковырять или лучше делать свое решение?

**Comment by oxxxxxy** [comment]
@mrzafod уалейкум асалам.
смотря для чего тебе. если быстрое решение как-нибудь, то это оно, но нужна смекалка чутка. или можно tradex попробовать, но там дока неполная, а кода много, лень разбирать было мне лично.

если сам хочешь доработать, то вперед, кода тут мало, он вполне понятен и прост. но это опять-таки время. тем более, если хочешь

а так, коротко вот.
МИНУСЫ:
-индюк на индюк накинуть нельзя нормально, есть смещение, т.к. привязывается каждый к одной оси координат. это придется учитывать при вычислении индюков( да, их самому над вычислять, формулы не на всё есть, лол, да ещё и неправильные часто попадаются, если с графиком биржи любой сравнить, крч, квест ещё один)

-есть проблема с прорисовкой и прокруткой чарта свечей, пришлось решить костылями в виде "чистки"( отдельно свечи обрезаешь нужные для отрисовки и вставляешь в либу эту, основной массив свечей отдельно ) и уменьшения зума через евент на скроллинг.

ПЛЮСЫ:
- т.к. ось времени тож одна, можно индюки с разными фреймами добавить к одному графику.

- передача евента с мыши на все чарты, легкость контроля его, модификации.

- да и в целом из-за простоты, легко в любое место влезть, хочешь патч, хочешь так меняй. оч гибко и быстро. кода в репе этой мало, разобраться легко как и чо работает.

вот, что у меня вышло, с учетом моих требований.
![image](https://github.com/project-nv/night-vision/assets/99099523/a8c72693-04ac-4e6d-b84a-0cab6edbae19)

**Comment by oxxxxxy** [comment]
> > вот что реально круто у либы твоей, так это простота.
> 
> Салам алейкум! Я так понял ты уже какое-то время используешь этот пакет. Можешь дать обратку? Стоит ее форкать и ковырять или лучше делать свое решение?

тебя спасибо говорить не учили?
