### ISSUE TITLE
Need Fibonacci Circle in charts.

### ISSUE THREAD

**Issue by nkroker** [project-nv/night-vision#123]
### Description

I need to draw a fib circle as an overlay similar to what Tradingview have 
https://in.tradingview.com/support/solutions/43000518159-fib-circles/

Is there any way to achieve this.

### Suggested solution

If there's nothing available, is there any workaround or is it be implemented as a new feature.

### Alternative

Suggest something here

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by vattevaii** [comment]
I implemented this with custom navyJS code.. I don't think we have features like drawing lines, circles and any other custom drawing in nightvision (I've seen some related code in the library but don't know how to use them, I copied the code in my repo then added it as a script for my first navyJS script)

```ts
propagate(...data: any): void
  draw(...data: any): void
  drawBotbar(...data: any): void
  drawSidebar(...data: any): void
  keydown(...data: any): void
  keypress(...data: any): void
  keyup(...data: any): void
  mouseup(...data: any): void
  mousedown(...data: any): void
  mousemove(...data: any): void
  mouseout(...data: any): void
  mouseover(...data: any): void
  click(...data: any): void
  legend(...data: any): void
  meta(...data: any): void
  dataFormat(...data: any): void
  yRange(...data: any): void
  preSampler(...data: any): void
  legendHtml(...data: any): void
  valueTracker(...data: any): void
  ohlc(...data: any): void
  ```
  
  these are the base functions which are used in a navy file.. where you also get `$events`,`$lib`,`$core` and some other variables (I forgot what), which you can use to get chart's current state to draw upon the chart

**Comment by nkroker** [comment]
Hi @vattevaii Is there any alternate for vue js means I want this functionality in vue js so is there any turn arround

**Comment by nkroker** [comment]
Hi @vattevaii 

Thanks for the input my issue is solved by this.
