### ISSUE TITLE
usage on NextJs

### ISSUE THREAD

**Issue by JustMankus** [project-nv/night-vision#15]
Hello,
Great library you building. Yet having trouble using it on NextJs framework.

Keep on receiving error while trying to initiate a chart.

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'context')

**Comment by C451** [comment]
HI, if you provide your actual code, this would be easier. 
For now there is no issue temple, so in the future you'll not be able to create issues without sample code. 

Ideally, I'd like to get a codesandboc with your case. We living in 2022, now it's possible ; )

**Comment by JustMankus** [comment]
Apologies. Seems that was due to packages. :)
