### ISSUE TITLE
Chart flickering on data update when using react.

### ISSUE THREAD

**Issue by frbju** [project-nv/night-vision#19]
![flicker](https://user-images.githubusercontent.com/55388455/204108937-2ce32ca8-f36b-46f8-b505-00d42eed57b6.gif)

Chart flickering when data updates. Looks like yExtent resets each time it gets new data.

code:

```
import React, { useEffect, useState, useRef } from 'react';
import { NightVision } from 'night-vision'

let chart;
const StockChart = (props) => {

	useEffect(() => {
		chart = new NightVision('stockchart', {
			autoResize: true,
		})
	}, [])

	useEffect(() => {
		if (props.data.length > 0) {
			chart.data = {
				panes: [
					{
						overlays: [
							{
								name: "APE / Tether US",
								type: "Candles",
								main: true,
								data: props.data.reverse()
							}]
					}
				],
			}
		}
	}, [props.data])
	return (
		<>
			<div id="stockchart"></div>
		</>
	);
}

export default StockChart;
```

**Comment by C451** [comment]
You made the whole data set reactive, but this lib was build to avoid this. You need to use partial updates https://nightvision.dev/guide/api/chart-api.html#chart-update-type-opt

**Comment by frbju** [comment]
thanks for this. Do you have an example on how to use chart.update('data') ?
Tried lots of things but non actually updates the data.

**Comment by C451** [comment]
Yes, when I add new chunk of data here, I call `update('data')` https://codesandbox.io/s/playing-around-10-0zh0jh?from-embed=&file=/main.js

**Comment by frbju** [comment]
Thank you. Got it working without react, But not with it . The main problem i have is that the DOM element is not created until mount. That means i need to create a div outside root and run root as absolute to overlay the chart with other components.  This way i can render both the chart and overlay buttons with react and pass data to the chart.  No the best solution but it works

**Comment by frbju** [comment]
Thank you
