### ISSUE TITLE
Overlays not visible when range < x

### ISSUE THREAD

**Issue by frbju** [project-nv/night-vision#21]
Add overlays to my chart and noticed that when x range is less than ? the SMA is not displayed.  When i zoom out it pops back in. Could this have something to do with "Spline" ?

Code:

![SMA-zoomed-out](https://user-images.githubusercontent.com/55388455/204579869-9326e3d4-6090-49f3-8fdb-baa2d0d0e521.jpg)
![SMA-zoomed-in](https://user-images.githubusercontent.com/55388455/204579875-4961a244-5b7f-496e-a5c4-8d94736b6c99.jpg)

**Comment by C451** [comment]
Hey, thank for testing, but we can really move faster with codesandbox samples (yes, it's free) 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/48596328/204585710-aa5eab5f-6afe-4f1b-82db-536d2a9ab934.png">

**Comment by frbju** [comment]
great thanks. made a hacky example ,will work more on it on sandbox 😊. it does not work the same as on my pc for some reason, will add the sma and fix the "no data tag" tomorrow.
https://codesandbox.io/embed/rough-frog-mixzxm?codemirror=1

**Comment by C451** [comment]
Already can see that you are not updating it correctly, you need something like https://medium.com/ottofellercom/how-to-make-react-js-not-that-reactive-d680392da02d
and `update` method.

**Comment by frbju** [comment]
https://codesandbox.io/s/react-night-vision-6vkjfo

This actually works with react, problem now is passing data to the component.  But for my case as it's built with socket.io i can just get the data right in the stockchart component.

Hopefully someone more skills than me can solve this :)

**Comment by C451** [comment]
You are using version 0.2.3 , `update('data')` was added in 0.2.4

**Comment by frbju** [comment]
updated 👍 forgot to change it back from testing

**Comment by frbju** [comment]
Would you say vue 3 would be an better option than react for this project?
at this point I have the option to choose as I'm not too invested.  or to just go vanilla

**Comment by C451** [comment]
I'd recommend Svelte, it's the fastest. (both performance-wise and development-wise)

**Comment by frbju** [comment]
oh ic. will have a look at that 😊

**Comment by frbju** [comment]
Moved all my code to Svelte and i have to say WOW.  way cleaner code! this will be my goto in the future. Thanks for that :)

If you don't mind as i'm new to svelte. Is this the correct way to mount the library?
It works but i'm just not sure if this is the best way.
```

<script>
    import { onMount } from "svelte";
    import { NightVision } from "night-vision";
    onMount(() => {
        let data = {
            panes: [
                {
                    overlays: [
                        {
                            name: "BTC-USD-221239",
                            type: "Candles",
                            main: true,
                            data: [],
                        },
                    ],
                },
            ],
        };
        let chart = new NightVision("stockchart", {
            autoResize: true,
        });
        chart.data = data;
    });
</script>

<div id="stockchart" />

```

**Comment by C451** [comment]
Yes, this is the way ; )
