### ISSUE TITLE
Hairline freezes when Developper Tools is opened ?

### ISSUE THREAD

**Issue by Jonarod** [project-nv/night-vision#22]
### Describe the bug

 When Developper Tools is opened, after zooming out on a random chart, hairline gets really laggy: it freezes and does not synchronise with the mouse cursor. As soon as Developper Tools is closed, hairline reactivity gets back to normal speed.

Feels like the hairline is causing a lot of side effects causing the tab to lag when dev tools is opened ?

### Reproduction

https://codesandbox.io/s/playing-around-3-voc5c6?from-embed

### Steps to reproduce

Open any of the 10 Getting Started sandbox's preview into a new Browser tab. Then open Dev Tools (F12). Then zoom the chart OUT. Then try to move the mouse over the chart. The hairline will lag. 

Note: I am on Macbook Pro M1 16Gb RAM, with only 1 Chrome tab opened (the one for the test, nothing else).

### Javascript Framework

no-framework (vanilla-js)

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C451** [comment]
Yes, I experience this too. Although I have the same notebook, and it is almost unnoticeable here. Can you test trading-vue-js? https://tvjsx.github.io/trading-vue-demo/  

Probably, the problem is with some dev-tool analytics, it is really hard to tell.

**Comment by Jonarod** [comment]
It has the same issue yes...

**Comment by C451** [comment]
https://stackoverflow.com/questions/60573388/react-app-slows-to-a-crawl-with-chrome-developer-tools-open-works-fine-in-incog

With profiling enabled it works smoothly indeed

**Comment by Jonarod** [comment]
I confirm after profiling it works smoothly. I let you close this issue if you feel like it is out of the scope and we should just enable profiling during dev or if you prefer considering it as a solvable issue :) Thank you for your lights !
