### ISSUE TITLE
Pane plotbands from settings or props

### ISSUE THREAD

**Issue by frbju** [project-nv/night-vision#27]
### Description

As a user i would like to be able to draw bands in the panes settings. Ex high / low bands for rsi, macd etc.  The reason to have the bands in Pane settings is because then you can draw any overlay and have the same bands.
![plotbands](https://user-images.githubusercontent.com/55388455/205965832-d93c09c5-cafb-4169-80b8-59d18cc81eab.jpg)

### Suggested solution

```
panes [
        {
            settings: {
                plotband: value 1,
                plotband: value 2
            }
            overlays: []
        }
    ]
```

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
https://github.com/project-nv/night-vision/blob/main/src/scripts/Range.navy#L13, it's just the settings window is not implemented.

**Comment by frbju** [comment]
oh I missed that. awesome thanks!
