### ISSUE TITLE
Non-passive event listner to a scroll-blocking 'wheel' event.

### ISSUE THREAD

**Issue by frbju** [project-nv/night-vision#28]
### Describe the bug

night-vision.js:5902 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
![evt](https://user-images.githubusercontent.com/55388455/206054135-e294548b-ab29-43fa-9cef-d409f9832230.jpg)

### Possible solution
https://github.com/angular/components/issues/4221#issuecomment-299872704

### Reproduction

x

### Steps to reproduce

x

### Javascript Framework

svelte

### Logs

night-vision.js:5902 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C451** [comment]
Do you get in in Chrome?

**Comment by frbju** [comment]
Chrome is correct 👍.  Sounds good, in my understanding it does not really affect the performance either.
