### ISSUE TITLE
Crosshair timestamp stops at last candle's timestamp instead of the expected future timestamp

### ISSUE THREAD

**Issue by Jonarod** [project-nv/night-vision#32]
### Describe the bug

When crosshair hovers above a candle that does not yet exists (in the future), the timestamp is stucked at the last timestamp of the dataset.

It should follow the expected timestamp based on timeframe inferred by `scan`.

Below, look at the timestamps, they are the same although on the second image, the crosshair is placed 2 candles' slots to the right of the last one:

<img width="445" alt="Timestamp of last candle" src="https://user-images.githubusercontent.com/6122703/208267105-a7273951-8a31-45b7-9965-e53d54797d62.png">

<img width="445" alt="Timestamp of expected next candle slot" src="https://user-images.githubusercontent.com/6122703/208267110-723349f9-9818-4088-bc33-310bff3b0541.png">

### Reproduction

https://codesandbox.io/s/playing-around-1-15lwqr?file=/main.js

### Steps to reproduce

In this sandbox, position the crosshair at the last date of the visible spline, then hover one "step" further to the right and compare the 2 timestamps: they are the same. They should be different, and the next "step" should actually be "guessed" to be last timestamp + 1 timeframe.

In that specific sandbox, the data ends at this timestamp: 1663477200000.
So the next future timestamp to be "guessed" should be 1663477200000 + 1 timeframe, in that specific case, the timeframe being 1Hour, the next expected data point should be at 1663477200000 + 3600000 = 1663480800000

### Javascript Framework

no-framework (vanilla-js)

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jonarod** [comment]
Correct me if I am wrong but as of 0.3.2 the issue is still here. Exactly the same: [https://codesandbox.io/s/playing-around-1-15lwqr?file=/main.js](https://codesandbox.io/s/playing-around-1-15lwqr?file=/main.js)

No?

**Comment by C451** [comment]
Yep.

**Comment by Jonarod** [comment]
So why close ? Does this mean this will stay out of the scope of `night-vision`?

**Comment by C451** [comment]
Coz `commit -m "fix #NN"`

**Comment by Jonarod** [comment]
So it was a mistake ? Why not re-open until a fix is found ?
