### ISSUE TITLE
Expiration hyper links in docs.

### ISSUE THREAD

**Issue by AHammerLine** [project-nv/night-vision#34]
### Describe the bug

Hi,  following [basic-configuration.md](https://github.com/project-nv/night-vision/blob/main/docs/docs/guide/intro/basic-configuration.md) in intro, there is a 404 ChartAPI link on bottom. 

The reason is the link (https://github.com/project-nv/night-vision/blob/main/guide/api/chart-api) is outdate, for now (2022.12.22) it should be [ChartAPI](https://github.com/project-nv/night-vision/blob/main/docs/docs/guide/api/chart-api.md)

Maybe author forgot to update hyper links after path changed?

### Reproduction

https://github.com/project-nv/night-vision/blob/main/guide/api/chart-api

### Steps to reproduce

At the end of page  [basic-configuration.md](https://github.com/project-nv/night-vision/blob/main/docs/docs/guide/intro/basic-configuration.md), click the [ChartAPI](https://github.com/project-nv/night-vision/blob/main/guide/api/chart-api).

### Javascript Framework

no-framework (vanilla-js)

### Logs

No code there.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C451** [comment]
Interesting, this work on the site https://nightvision.dev/guide/intro/basic-configuration.html
(which I'm recommending, bc we have a great search bar now)

**Comment by AHammerLine** [comment]
> Interesting, it works on the site https://nightvision.dev/guide/intro/basic-configuration.html (which I'm recommending, bc we have a great search bar now)

Thanks, I just know that!
