### ISSUE TITLE
Render/Input bug when using event listeners

### ISSUE THREAD

**Issue by Swoorup** [project-nv/night-vision#41]
### Describe the bug

When subscribing to events i.e 

```javascript
chart.events.on("chart:range-changed", (event) => {
  const dataStart = data.panes[0].overlays[0].data[0][0];
  const from = event[0];
  const to = event[1];
  console.log(
    `DataStart: ${new Date(dataStart).toUTCString()}, ViewStart: ${new Date(
      from
    ).toUTCString()}, ViewEnd: ${new Date(to).toUTCString()}`
  );
});
```

It appears that NV chart becomes buggy:
* It fails to display some or most of the candles when scrolling despite the data being there. See repro link's console. 
  Data begins at `Mon, 02 Jan 2023 16:51:18 GMT` but it is not visible. Removing the listener solves the issue.
* Zooming is also unresponsive, at least on testpad, and 

### Reproduction

https://codesandbox.io/s/playing-around-4-forked-fkl33n?from-embed=&file=/main.js:601-933

### Javascript Framework

no-framework (vanilla-js)

### Logs

```
night-vision.js:6413 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ night-vision.js:6413
onEvent @ night-vision.js:6386
listeners @ night-vision.js:6568
setup @ night-vision.js:6555
attach @ night-vision.js:7315
(anonymous) @ night-vision.js:7678
```

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C451** [comment]
Should be `"app:$range-update"`. 
Each event component should have a unique name

**Comment by Swoorup** [comment]
You are right, I am closing this.
