### ISSUE TITLE
Lock X-axis

### ISSUE THREAD

**Issue by Jonarod** [project-nv/night-vision#49]
### Description

Is there a way to lock x-axis completely an scroll AND on drag/pan ?
I reckon tvjs might have something like this in the form of an event maybe ? (not sure thought)

### Suggested solution

Something like `events.emit('scroll_lock', true)`

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Not implemented yet, have to look into tvjs code.

**Comment by C451** [comment]
Implemented in 0.4.0
