### ISSUE TITLE
Gap beetween dates

### ISSUE THREAD

**Issue by Fr3sto** [project-nv/night-vision#63]
### Describe the bug

The problem is connecting adjacent bars with difference date. What do I need to write to fix this? 
![image](https://user-images.githubusercontent.com/29036818/230623145-a27f3572-608a-4cff-83f3-8540d3e89975.png)

### Reproduction

https://nightvision.dev/guide/intro/10-basic-examples.html

### Javascript Framework

no-framework (vanilla-js)

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C451** [comment]
The only way
https://nightvision.dev/guide/intro/10-basic-examples.html#_5-displaying-stock-data
