### ISSUE TITLE
Cursor sync

### ISSUE THREAD

**Issue by wk1210** [project-nv/night-vision#74]
### Description

Hello, I have a question about cursor synchronization. Based on my testing with the code examples, I found that cursor synchronization is done based on the xy coordinate axis. However, I would like to achieve synchronization based on timestamps. Can night vision accomplish this? Do you have any suggestions? Thank you for your response.

### Suggested solution

Added some example code showing how to sync cursor based on timestamp.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mariusvigariu** [comment]
You should be able to obtain your x/time coordinate using the [mapping functions](https://nightvision.dev/guide/main-comp/layout.html#mapping-functions)

**Comment by wk1210** [comment]
> You should be able to obtain your x/time coordinate using the [mapping functions](https://nightvision.dev/guide/main-comp/layout.html#mapping-functions)
Thank you for your response. I have solved my problem using mapping functions. Thanks again.
