### ISSUE TITLE
Log scale won't work

### ISSUE THREAD

**Issue by mariusvigariu** [project-nv/night-vision#76]
### Describe the bug

Adding `log = true` to scale settings will result in an error:

```
chart.data = {
  panes: [
    {
      overlays: [
        {
          // ...
        },
      ],
      settings: {
        scales: {
          A: {
            log: true,
          },
        },
      },
    },
  ],
};
```

this patch would apparently fix the issue:

```
diff --git a/src/core/gridScale.js b/src/core/gridScale.js
index e0e1aa9..be17b78 100644
--- a/src/core/gridScale.js
+++ b/src/core/gridScale.js
@@ -255,6 +255,10 @@ export default function Scale(id, src, specs) {
         self.$_mult = dollarMult()
         self.ys = []
 
+        const ov = ovs[0]
+        console.log(ov)
+        const data = ov.dataSubset
+
         if (!data.length) return
 
         let v = Math.abs(data[data.length - 1][1] || 1)
@@ -316,6 +320,8 @@ export default function Scale(id, src, specs) {
         return y$
     }
 
+    let MAX_INT = Number.MAX_SAFE_INTEGER
+
     // Make log scale levels look great again
     function logRounder(x, quality) {
         let s = Math.sign(x)

```

but the values would still not be properly rendered on the sidebar

![image](https://github.com/project-nv/night-vision/assets/16646978/4754b925-d1af-4ea4-bbdb-1b0b15e4ac94)

and in the example below the first candle has a huge upper wick which gets rendered till infinite (see legend vs sidebar)

![image](https://github.com/project-nv/night-vision/assets/16646978/4c02bfbd-b29d-426b-834b-c1db0daae743)

### Reproduction

https://nightvision.dev/guide/intro/getting-started.html

### Steps to reproduce

Follow the [getting started steps](https://nightvision.dev/guide/intro/getting-started.html) then set settings in main.js

```
      settings: {
        scales: {
          A: {
            log: true,
          },
        },
```

### Javascript Framework

vue

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Antc1993** [comment]
Hi, did you find a solution? I have the same problem.

**Comment by mariusvigariu** [comment]
Looks like recent commits fix some parts of the issue. I still see room for improvement for cases where the sidebar needs to render small values, eg:

![image](https://github.com/project-nv/night-vision/assets/16646978/13dedd99-df1f-4ff1-bfe4-9b02f010d5ae)

I've dig a little bit in the code and I think [Scale.ys](https://github.com/project-nv/night-vision/blob/main/src/core/gridScale.js#L260) needs to be tweaked a little bit, but dont have the time to understand the code properly.

@C451 do you have some pointers on this? I could make a PR with the right guidance

**Comment by C451** [comment]
I fixed log scale a bit, but the y-transforms work incorrectly. TODO for the future
