### ISSUE TITLE
How to change the zoom level

### ISSUE THREAD

**Issue by wk1210** [project-nv/night-vision#77]
### Description

When loading 1000 candlesticks, the default zoom level displays too few candlesticks, requiring mouse scrolling to show more. How can I change this? Also, when loading candlesticks in real-time, a fullReset call is necessary to refresh. I would like to default to displaying more candlesticks when refreshing. Do you have any suggestions?

### Suggested solution

<img width="1901" alt="image" src="https://github.com/project-nv/night-vision/assets/115026712/f7588e1d-078e-40fd-9b8c-b15b1e0e8d2f">
<img width="1900" alt="image" src="https://github.com/project-nv/night-vision/assets/115026712/a454ee27-6a2a-473c-901f-4781529e8631">

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DmitrijLVs** [comment]
You can use 'DEFAULT_LEN' property to control how many candlesticks you want to show - https://nightvision.dev/guide/api/chart-config.html#config-default-len

To update data in real-time you don't need to update full chart, just data: `this.chart.update('data');`

Hope it helps

**Comment by wk1210** [comment]
> You can use 'DEFAULT_LEN' property to control how many candlesticks you want to show - https://nightvision.dev/guide/api/chart-config.html#config-default-len
> 
> To update data in real-time you don't need to update full chart, just data: `this.chart.update('data');`
> 
> Hope it helps

Thank you for your response, DEFAULT_LEN is working and it has resolved the issue. I really appreciate your help. Regarding your suggestion of using `this.chart.update('data')`, I tested it and found that the data is indeed updated, but the x-axis remains unchanged. So, currently, I am using `this.chart.fullReset() `which allows me to update the x-axis.
