### ISSUE TITLE
Abount fullReset flicker

### ISSUE THREAD

**Issue by wk1210** [project-nv/night-vision#79]
### Description

When using fullReset for updating, the screen flickers, which is a problem. Currently, I can only use fullReset for updating because using chart.update("data") only updates the candles, and the x-axis does not update simultaneously.

### Suggested solution

Is there any other update interface that can meet the requirements or prevent fullReset from flickering?

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Yeah, this is a known problem. No solution for now (it happens because we need to wait for a response from an overlay to detect the dimensions of the pane. But it takes one tick, so you see the result of the adjustment)

**Comment by wk1210** [comment]
Sure, I understand. If Night Vision fixes this issue in the future, please include a mention of it in the version update notes. Thank you again for your response.
