### ISSUE TITLE
Custom HTML tooltips

### ISSUE THREAD

**Issue by nchanged** [project-nv/night-vision#85]
### Description

Custom HTML tooltips

### Suggested solution

chart.events.on('app:cursor-changed', (e) => {});

there should be a method which would allow getting the current candle under the cursor.
Would be nice to have that candle coordinates relative to the main div object so it's easier to place something on top of it.

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Although you supposed to use an overlay for that, I've added a method in cursor event

**Comment by C451** [comment]
https://github.com/project-nv/night-vision/commit/2667bd25b6f88d750ac340422cf520bc3a5e6801
