### ISSUE TITLE
Nuxt3 Scripts Not Working

### ISSUE THREAD

**Issue by xtrmus** [project-nv/night-vision#86]
### Describe the bug

I have a javascript nuxt test project to play with the nv library. I've created a test page which looks like:

There is no problem in the code or console section.

Code : 
![image](https://github.com/project-nv/night-vision/assets/24972453/209e2f42-2a3d-4591-bd11-71dae5cb9180)
![image](https://github.com/project-nv/night-vision/assets/24972453/eb321eb5-ef85-48b8-8c85-c68cc85f1c04)

RSI Navy:
![image](https://github.com/project-nv/night-vision/assets/24972453/97ed7039-9e2f-4fa3-a61e-746ea67dfb7c)

The RSI dashboard opens. However, no data is coming. There is an error only in the nuxt server.

![image](https://github.com/project-nv/night-vision/assets/24972453/56e2e76a-a77f-429c-9219-64945fe84863)

![image](https://github.com/project-nv/night-vision/assets/24972453/28addbfa-66a1-446e-9b01-6973a985722a)

### Reproduction

https://nightvision.dev/guide/built-in-indicators/RSI.html

### Javascript Framework

vue

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mariusvigariu** [comment]
This does not look like a Nuxt issue, more like how you define your RSI script. When pushing a pane, try sending an empty array for overlays and for scripts something like `[{ type: 'RSI' }]` should do the trick. 

Also you don't need to import RSI as it's already built in.

**Comment by C451** [comment]
Seems solved
