### ISSUE TITLE
Where exactly am I going wrong?

### ISSUE THREAD

**Issue by xtrmus** [project-nv/night-vision#87]
### Describe the bug

https://codesandbox.io/s/nostalgic-saha-zrxwr2?file=/src/main.js

I got the default codes from your github project.

Isn't normally the EMA indicator supposed to be above the panel?

Is there something I missed or didn't do? I've been trying for days and couldn't figure it out.

I would be glad if you help.

### Reproduction

https://github.com/project-nv/night-vision

### Javascript Framework

no-framework (vanilla-js)

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Antc1993** [comment]
```
import IndicadorName from '/IndicadorName .navy'
{
     panes: [
        {
      
            overlays: [
                {
                    name: "…", // Overlay name
                    type: "…", // Overlay type
                    data: […], // Time-series: [[<time>, value, …], …]
                    settings: {…}, // Overlay settings
                    props: {…}, // Overlay props
                
                },
                {
                  name: "IndicadorName", // Overlay name
                  type: "IndicadorName", // Overlay type
                }

            ],
            settings: {…}, 
        }
    ]
    scripts: [IndicadorName ]
}

```

**Comment by C451** [comment]
Looks good to me (need to use 0.4.0 in codesandbox)
<img width="521" alt="image" src="https://github.com/project-nv/night-vision/assets/48596328/615de2a0-e041-4642-aa65-c478e687bdcb">
