### ISSUE TITLE
Integrate eslint

### ISSUE THREAD

**Issue by mariusvigariu** [project-nv/night-vision#94]
### Description

As a dev I would like to have eslint integrated to make the code more readable

### Suggested solution

Integrate eslint, keep defaults and add the following rules:

```
cat .eslintrc
{
  "rules": {
    "comma-dangle": ["error", "always-multiline"]
  }
}
```

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by C451** [comment]
Add eslint for checking commas? hmmm

**Comment by mariusvigariu** [comment]
Thats just an example for the rc file, it does not mean its only checking commas :) 

I strongly suggest integrating eslint as it will make the code much more readable, thus easier to maintain and extend in the future
