### ISSUE TITLE
Create custom indicators

### ISSUE THREAD

**Issue by black-sec** [project-nv/night-vision#99]
### Describe the bug

Hello good time
I think this question of mine is the question of many friends
Please write a sample program to start working as an indicator that can display the cross of two EMAs in the chart.
Thank you for writing this sample program

### Reproduction

https://nightvision.dev/

### Javascript Framework

no-framework (vanilla-js)

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C451** [comment]
Hey man, I think you should start with something more simple like lightweight-charts. Given the questions you ask, it will be very hard to use this project.
